services:
  db:
    image: postgres:15
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 20s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freterapido-backend-api
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # FreteRapido API variables (with explicitly set values for clarity)
      - FRETE_RAPIDO_API_URL=https://sp.freterapido.com/api/v3/quote/simulate
      - CNPJ=25438296000158
      - REGISTERED_NUMBER=25438296000158
      - FRETE_RAPIDO_TOKEN=1d52a9b6b78cf07b08586152459a5c90
      - PLATFORM_CODE=5AKVkHqCn
      - ZIPCODE=29161376
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
